const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const store={get(k,d=null){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
const posters=[
["Solo Leveling","https://images.unsplash.com/photo-1545231027-637d2f6210f8?auto=format&fit=crop&w=600&q=80","9.4","Ação • Fantasia"],
["One Piece","https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=600&q=80","9.1","Aventura • Comédia"],
["Naruto Shippuden","https://images.unsplash.com/photo-1607604276583-eef5b076aa5f?auto=format&fit=crop&w=600&q=80","8.8","Ação • Drama"],
["Demon Slayer","https://images.unsplash.com/photo-1606115915090-be18fea23ec7?auto=format&fit=crop&w=600&q=80","8.7","Ação • Fantasia"],
["Jujutsu Kaisen","https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80","8.7","Ação • Sobrenatural"],
["Attack on Titan","https://images.unsplash.com/photo-1518709594023-6eab9bab7b23?auto=format&fit=crop&w=600&q=80","9.0","Drama • Militar"],
["Bleach","https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=600&q=80","8.5","Ação • Fantasia"],
["Blue Lock","https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=600&q=80","8.4","Esporte • Drama"],
["Chainsaw Man","https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?auto=format&fit=crop&w=600&q=80","8.7","Ação • Terror"],
["Frieren","https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=600&q=80","9.0","Fantasia • Aventura"],
["Dragon Ball Super","https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=80","8.6","Ação • Aventura"],
["The Apothecary Diaries","https://images.unsplash.com/photo-1524985069026-dd778a71c7b4?auto=format&fit=crop&w=600&q=80","8.9","Drama • Mistério"]
];
const avatars=[
"https://i.pravatar.cc/160?img=12","https://i.pravatar.cc/160?img=5","https://i.pravatar.cc/160?img=11","https://i.pravatar.cc/160?img=32",
"https://i.pravatar.cc/160?img=44","https://i.pravatar.cc/160?img=47","https://i.pravatar.cc/160?img=49","https://i.pravatar.cc/160?img=52",
"https://i.pravatar.cc/160?img=58","https://i.pravatar.cc/160?img=60","https://i.pravatar.cc/160?img=64","https://i.pravatar.cc/160?img=68"
];
const genres=["Ação","Aventura","Comédia","Drama","Fantasia","Romance","Terror","Mistério","Sobrenatural","Esporte","Isekai","Escolar"];
const days=["Seg","Ter","Qua","Qui","Sex","Sáb","Dom"];

let state={page:location.hash.slice(1)||"home",user:store.get("ad_user",null),list:store.get("ad_list",[]),history:store.get("ad_history",[]),avatar:store.get("ad_avatar",avatars[0]),theme:store.get("ad_theme","dark")};

function toast(msg,type="ok"){const d=document.createElement("div");d.className="toast "+type;d.textContent=msg;$("#toast-root").append(d);setTimeout(()=>d.remove(),2600)}
function nav(page){location.hash=page}
window.addEventListener("hashchange",()=>{state.page=location.hash.slice(1)||"home";render()});

function layout(inner){
 const navs=[["home","⌂","Início"],["anime","◈","Animes"],["films","▣","Filmes"],["genres","✦","Gêneros"],["calendar","▦","Calendário"],["list","♡","Minha Lista"],["history","◷","Histórico"],["profile","◉","Perfil"]];
 return `<div class="shell"><aside class="sidebar">
  <div class="brand"><img src="/assets/animedragon-dragon.png"><div><strong>AnimeDragon</strong><small>Ultra Remastered</small></div></div>
  <div class="nav-title">Explorar</div><nav class="nav">${navs.map(n=>`<button class="${state.page===n[0]?'active':''}" data-nav="${n[0]}"><i class="ico">${n[1]}</i><span>${n[2]}</span></button>`).join("")}</nav>
  <div class="nav-title">Sistema</div><nav class="nav"><button data-nav="settings"><i class="ico">⚙</i><span>Configurações</span></button><button data-nav="notifications"><i class="ico">♢</i><span>Notificações</span></button></nav>
  <div class="sidebar-bottom"><div class="account-mini">${userMini()}</div><nav class="nav"><button id="logout"><i class="ico">⇥</i><span>Sair</span></button></nav></div>
 </aside><main class="main">
 <header class="topbar"><div class="search"><span>⌕</span><input id="global-search" placeholder="Buscar animes, filmes, gêneros..." value="${state.search||""}"></div>
 <div class="top-actions"><button class="icon-btn" data-nav="notifications">♧</button><button class="icon-btn" id="theme">☾</button><button class="profile-chip" data-nav="profile"><img class="avatar" src="${state.avatar}"><div><b>${state.user?.name||"Visitante"}</b><small>${state.user?"Premium":"Conta demo"}</small></div></button></div></header>
 <div class="content">${inner}</div><div class="mobile-nav">${navs.slice(0,5).map(n=>`<button class="${state.page===n[0]?'active':''}" data-nav="${n[0]}"><b>${n[1]}</b>${n[2]}</button>`).join("")}</div>
 </main></div>`;
}
function userMini(){return state.user?`<div class="user-row"><img class="avatar" src="${state.avatar}"><div><b>${esc(state.user.name)}</b><small>${esc(state.user.email)}</small></div></div>`:`<button class="primary" style="width:100%;padding:9px" id="login-open">Entrar / Criar conta</button>`}
function esc(x=""){return String(x).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}

function card(p,i){return `<article class="card" data-anime="${i}"><img class="poster" src="${p[1]}" loading="lazy"><div class="card-body"><div class="card-title">${p[0]}</div><div class="card-sub">${p[3]}</div><div class="card-meta"><span class="rating">★ ${p[2]}</span><span>HD</span></div></div></article>`}
function cards(items=posters){return `<div class="cards">${items.map((p,i)=>card(p,i)).join("")}</div>`}
function section(title,content,action="Ver todos"){return `<section class="section"><div class="section-head"><h2>${title}</h2><small>${action}</small></div>${content}</section>`}

function home(){
 const continueItems=[["Solo Leveling",68,7],["One Piece",42,1023],["Naruto Shippuden",76,284],["Demon Slayer",31,11]];
 return `<div class="layout"><div>
 <section class="hero"><div class="hero-content"><span class="badge">EM DESTAQUE</span><h1>Solo Leveling</h1><p>Após um incidente em uma masmorra, Sung Jin-Woo ganha a chance de evoluir infinitamente. Sua jornada para se tornar o mais forte começa agora.</p><div class="meta"><span class="rating">★ 9.4/10</span><span>2024</span><span>12+</span><span>Ação</span><span>Fantasia</span></div><div class="actions"><button class="primary" data-play="Solo Leveling">▶ Assistir Agora</button><button class="secondary" data-list="Solo Leveling">＋ Minha Lista</button></div></div></section>
 ${section("🔥 Em Alta",cards())}
 ${section("◷ Continue Assistindo",`<div class="continue-grid">${continueItems.map((x,i)=>`<div class="continue" data-play="${x[0]}"><img src="${posters[i][1]}"><div><b style="font-size:11px">${x[0]}</b><small style="display:block;color:#7292b0;margin-top:5px">Episódio ${x[2]}</small><div class="progress"><i style="width:${x[1]}%"></i></div><small style="color:#10b8ff">${x[1]}%</small></div></div>`).join("")}</div>`)}
 ${section("🚀 Lançamentos",cards(posters.slice(5).concat(posters.slice(0,3))))}
 ${section("🎭 Gêneros",`<div class="genre-grid">${genres.slice(0,8).map(g=>`<div class="genre" data-genre="${g}">${g}</div>`).join("")}</div>`)}
 </div><aside class="right-rail">${rail()}</aside></div>`;
}
function rail(){return `<div class="rail-card"><h3>🏆 Em Destaque</h3>${posters.slice(0,5).map((p,i)=>`<div class="rank"><span class="rank-num">#${i+1}</span><img src="${p[1]}"><div><b>${p[0]}</b><small>${p[3]}</small><small class="rating">★ ${p[2]}</small></div></div>`).join("")}</div>
<div class="rail-card"><h3>👤 Minha Conta</h3>${state.user?`<div class="user-row"><img class="avatar" src="${state.avatar}"><div><b>${esc(state.user.name)}</b><small>Premium • nível 12</small></div></div><div class="stat-grid" style="margin-top:12px"><div class="stat"><b>${state.list.length}</b><small>Na minha lista</small></div><div class="stat"><b>${state.history.length}</b><small>Histórico</small></div></div>`:`<p style="color:#7895b3;font-size:11px;line-height:1.5">Crie sua conta para salvar lista, progresso, histórico, avatar e preferências em todos os dispositivos.</p><button class="primary" style="width:100%" id="login-open">Criar conta</button>`}</div>
<div class="rail-card"><h3>🔄 Sistema</h3><div class="setting-row"><span style="font-size:11px">TMDB</span><b style="color:#20d99b;font-size:10px">● Conectado</b></div><div class="setting-row"><span style="font-size:11px">Catálogo</span><b style="color:#20d99b;font-size:10px">● Atualizado</b></div><div class="setting-row"><span style="font-size:11px">Legendas</span><b style="color:#20d99b;font-size:10px">● Automáticas</b></div></div>`}

function catalog(kind="anime"){
 const title=kind==="films"?"Filmes":"Catálogo de Animes";
 return `<div class="page-title">${title}</div><div class="subline">Explore títulos, filtros, gêneros e lançamentos.</div>
 <div class="filters">${["Todos","Ação","Aventura","Comédia","Drama","Fantasia","Romance","Terror"].map((x,i)=>`<button class="filter ${i===0?'active':''}" data-filter="${x}">${x}</button>`).join("")}</div>
 <div id="catalog-results" class="catalog-grid">${posters.concat(posters.slice(0,5)).map((p,i)=>card(p,i)).join("")}</div>`;
}
function genresPage(){return `<div class="page-title">Gêneros</div><div class="subline">Escolha um gênero para filtrar o catálogo.</div><div class="genre-grid">${genres.map(g=>`<div class="genre" data-genre="${g}"><b>${g}</b><small style="display:block;color:#6689a8;margin-top:5px">${8+g.length} títulos</small></div>`).join("")}</div>`}
function calendar(){return `<div class="page-title">Calendário de Lançamentos</div><div class="subline">Acompanhe novos episódios e estreias.</div><div class="calendar">${days.concat(days).map((d,i)=>`<div class="day"><strong>${d} • ${i+1}</strong><div class="release"><b>${posters[i%posters.length][0]}</b><small>Episódio ${10+i}</small></div>${i%2?`<div class="release"><b>${posters[(i+3)%posters.length][0]}</b><small>Novo episódio</small></div>`:""}</div>`).join("")}</div>`}
function listPage(){const names=state.list.length?state.list:[];return `<div class="page-title">Minha Lista</div><div class="subline">Seus favoritos ficam salvos neste navegador no modo demonstração.</div>${names.length?cards(posters.filter(p=>names.includes(p[0]))):`<div class="empty">Sua lista está vazia.<br><br><button class="primary" data-nav="anime">Explorar catálogo</button></div>`}`}
function historyPage(){return `<div class="page-title">Histórico</div><div class="subline">Continue exatamente de onde parou.</div>${state.history.length?`<div class="continue-grid">${state.history.map((h,i)=>`<div class="continue" data-play="${h}"><img src="${posters[i%posters.length][1]}"><div><b>${h}</b><small style="display:block;color:#7292b0;margin-top:5px">Última sessão salva</small><div class="progress"><i style="width:${40+i*11}%"></i></div></div></div>`).join("")}</div>`:`<div class="empty">Nenhum título no histórico ainda. Comece a assistir para criar seu histórico.</div>`}`}
function profile(){
 if(!state.user)return `<div class="empty"><h2>Seu perfil</h2><p>Entre ou crie uma conta para editar seu perfil.</p><button class="primary" id="login-open">Entrar / Criar conta</button></div>`;
 return `<div class="page-title">Meu Perfil</div><div class="subline">Conta, avatar, preferências e informações pessoais.</div><div class="profile-page">
 <aside class="profile-cover"><img class="big-avatar" src="${state.avatar}"><h2>${esc(state.user.name)}</h2><p style="color:#7895b3;font-size:11px">${esc(state.user.email)}</p><span class="badge">★ PREMIUM</span><div class="stat-grid" style="margin-top:18px"><div class="stat"><b>${state.list.length}</b><small>Lista</small></div><div class="stat"><b>${state.history.length}</b><small>Histórico</small></div></div></aside>
 <section class="rail-card" style="margin:0"><div class="tabs"><button class="tab active">Perfil</button><button class="tab">Avatar</button><button class="tab">Preferências</button></div>
 <div class="form-grid"><div class="field"><label>Nome de usuário</label><input id="pf-name" value="${esc(state.user.name)}"></div><div class="field"><label>E-mail</label><input id="pf-email" value="${esc(state.user.email)}"></div><div class="field"><label>País</label><select id="pf-country"><option>Brasil</option><option>Portugal</option><option>Japão</option><option>Estados Unidos</option></select></div><div class="field"><label>Idioma</label><select><option>Português (BR)</option><option>English</option><option>日本語</option></select></div><div class="field full"><label>Bio</label><textarea id="pf-bio" placeholder="Conte um pouco sobre você...">${esc(state.user.bio||"")}</textarea></div><div class="field full"><label>Escolha seu avatar</label><div class="avatar-grid">${avatars.concat(state.user.customAvatars||[]).map(a=>`<button class="avatar-choice ${a===state.avatar?'selected':''}" data-avatar="${a}"><img src="${a}"></button>`).join("")}</div><input id="avatar-upload" type="file" accept="image/*" style="margin-top:10px;color:#7895b3"></div><div class="full actions"><button class="primary" id="save-profile">Salvar Alterações</button></div></div></section></div>`;
}
function settings(){return `<div class="page-title">Configurações</div><div class="subline">Controle reprodução, conta, privacidade, notificações e integração.</div><div class="settings"><aside class="settings-nav">${["Conta","Aparência","Player","Notificações","Privacidade","TMDB","Sobre"].map((x,i)=>`<button class="${i===0?'active':''}">${x}</button>`).join("")}</aside><section class="rail-card" style="margin:0"><h2 style="font-size:16px">Preferências</h2>${[["Reprodução automática",true],["Legendas automáticas",true],["Notificar novos episódios",true],["Lembrar progresso",true],["Modo escuro",true],["Dados analíticos",false]].map(x=>`<div class="setting-row"><div><b style="font-size:12px">${x[0]}</b><small style="display:block;color:#6f8da9;margin-top:3px">Configuração salva automaticamente</small></div><button class="switch ${x[1]?'on':''}"></button></div>`).join("")}<div class="setting-row"><div><b style="font-size:12px">TMDB API</b><small style="display:block;color:#6f8da9;margin-top:3px">A chave deve ficar no Worker/Secret, nunca no navegador.</small></div><b style="color:#20d99b;font-size:10px">● Arquitetura pronta</b></div></section></div>`}
function notifications(){return `<div class="page-title">Notificações</div><div class="subline">Atualizações importantes do AnimeDragon.</div>${["Novo episódio de One Piece disponível","Catálogo atualizado pelo TMDB","Seu perfil foi sincronizado","Novo lançamento adicionado ao calendário","Backup de preferências concluído"].map((x,i)=>`<div class="rail-card"><b style="font-size:12px">${x}</b><small style="display:block;color:#6d8fac;margin-top:5px">${i+1} hora${i?"s":""} atrás</small></div>`).join("")}`}
function searchPage(q){const res=posters.filter(p=>p[0].toLowerCase().includes(q.toLowerCase())||p[3].toLowerCase().includes(q.toLowerCase()));return `<div class="page-title">Busca</div><div class="subline">Resultados para <b>${esc(q)}</b></div>${res.length?`<div class="catalog-grid">${res.map((p,i)=>card(p,i)).join("")}</div>`:`<div class="empty">Nenhum resultado local. Em produção, esta busca será encaminhada ao serviço TMDB.</div>`}`}

function render(){
 const p=state.page;
 let inner=p==="home"?home():p==="anime"?catalog("anime"):p==="films"?catalog("films"):p==="genres"?genresPage():p==="calendar"?calendar():p==="list"?listPage():p==="history"?historyPage():p==="profile"?profile():p==="settings"?settings():p==="notifications"?notifications():p==="search"&&state.search?searchPage(state.search):home();
 $("#app").innerHTML=layout(inner); bind();
}
function bind(){
 $$("[data-nav]").forEach(b=>b.onclick=()=>nav(b.dataset.nav));
 $$("[data-anime]").forEach(c=>c.onclick=()=>openDetails(posters[+c.dataset.anime]));
 $$("[data-play]").forEach(b=>b.onclick=()=>openPlayer(b.dataset.play));
 $$("[data-list]").forEach(b=>b.onclick=()=>toggleList(b.dataset.list));
 $$("[data-genre]").forEach(b=>b.onclick=()=>{state.search=b.dataset.genre;nav("search")});
 const gs=$("#global-search"); if(gs){gs.onkeydown=e=>{if(e.key==="Enter"&&gs.value.trim()){state.search=gs.value.trim();nav("search")}}}
 const lo=$("#logout");if(lo)lo.onclick=()=>{state.user=null;store.set("ad_user",null);toast("Sessão encerrada");render()};
 const login=$("#login-open");if(login)login.onclick=loginModal;
 const theme=$("#theme");if(theme)theme.onclick=()=>toast("Tema escuro já está ativo.");
 $$(".filter").forEach(b=>b.onclick=()=>{$$(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");toast("Filtro aplicado: "+b.textContent)});
 $$(".switch").forEach(b=>b.onclick=()=>b.classList.toggle("on"));
 $$(".avatar-choice").forEach(b=>b.onclick=()=>{state.avatar=b.dataset.avatar;render()});
 const save=$("#save-profile");if(save)save.onclick=()=>{state.user.name=$("#pf-name").value.trim()||"Usuário";state.user.email=$("#pf-email").value.trim();state.user.bio=$("#pf-bio").value;store.set("ad_user",state.user);store.set("ad_avatar",state.avatar);toast("Perfil salvo com sucesso");render()};
 const upload=$("#avatar-upload");if(upload)upload.onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>2_500_000)return toast("Use uma imagem de até 2,5 MB","err");const r=new FileReader();r.onload=()=>{state.user.customAvatars=[...(state.user.customAvatars||[]),r.result];state.avatar=r.result;store.set("ad_user",state.user);store.set("ad_avatar",state.avatar);render();toast("Avatar enviado e salvo")};r.readAsDataURL(f)};
}
function toggleList(name){state.list=state.list.includes(name)?state.list.filter(x=>x!==name):[...state.list,name];store.set("ad_list",state.list);toast(state.list.includes(name)?"Adicionado à sua lista":"Removido da sua lista")}
function openDetails(p){$("#modal-root").innerHTML=`<div class="modal-back"><div class="modal"><div class="modal-head"><div><span class="badge">TMDB • DEMO</span><h2>${p[0]}</h2><div class="subline">${p[3]} • ★ ${p[2]} • 2024</div></div><button class="close" id="mclose">×</button></div><div style="display:grid;grid-template-columns:170px 1fr;gap:18px"><img class="poster" src="${p[1]}" style="border-radius:12px"><div><p style="color:#9ab1c8;line-height:1.6;font-size:12px">Página detalhada preparada para receber sinopse, elenco, trailers, temporadas, episódios, avaliações, gêneros e metadados sincronizados automaticamente.</p><div class="section-head"><h2>Temporadas</h2></div><div class="filters">${[1,2,3,4].map((x,i)=>`<button class="filter ${i===0?'active':''}" data-season="${x}">Temporada ${x}</button>`).join("")}</div><div class="section-head"><h2>Episódios</h2></div><div class="episode-grid">${Array.from({length:24},(_,i)=>`<button class="episode" data-ep="${i+1}">EP ${i+1}</button>`).join("")}</div></div></div></div></div>`;$("#mclose").onclick=closeModal;$$("[data-ep]").forEach(b=>b.onclick=()=>openPlayer(p[0],+b.dataset.ep))}
function closeModal(){$("#modal-root").innerHTML=""}
function openPlayer(title,ep=1){state.history=[title,...state.history.filter(x=>x!==title)].slice(0,30);store.set("ad_history",state.history);$("#modal-root").innerHTML=`<div class="player"><div class="player-top"><b>AnimeDragon • ${esc(title)} • Episódio ${ep}</b><button class="player-btn" id="player-close">✕ Fechar</button></div><video id="demo-video" controls autoplay muted playsinline src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4"></video><div class="player-bottom"><div class="player-progress" id="pbar"><i></i></div><div class="player-controls"><button class="player-btn" id="prev">◀</button><button class="player-btn" id="next">▶</button><button class="player-btn" id="fs">⛶ Tela cheia</button><select class="player-select"><option>1080p</option><option>720p</option><option>480p</option></select><select class="player-select"><option>Português (BR)</option><option>English</option><option>Español</option></select><span style="margin-left:auto;color:#a5bfd6;font-size:11px">Player independente • legendas automáticas preparadas</span></div></div></div>`;$("#player-close").onclick=closeModal;$("#fs").onclick=()=>$("#demo-video").requestFullscreen?.();$("#next").onclick=()=>toast("Próximo episódio preparado");$("#prev").onclick=()=>toast("Episódio anterior preparado");const v=$("#demo-video"),bar=$("#pbar"),fill=$("i",bar);v.ontimeupdate=()=>{fill.style.width=(v.currentTime/v.duration*100||0)+"%"};bar.onclick=e=>{v.currentTime=(e.offsetX/bar.clientWidth)*v.duration}}
async function hashPass(password){const enc=new TextEncoder();const salt=crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt,iterations:120000,hash:"SHA-256"},key,256);return {salt:[...salt],hash:[...new Uint8Array(bits)]}}
function loginModal(){ $("#modal-root").innerHTML=`<div class="modal-back"><div class="modal small"><div class="modal-head"><div><span class="badge">CONTA ANIMEDRAGON</span><h2>Entrar ou criar conta</h2></div><button class="close" id="mclose">×</button></div><div class="tabs"><button class="tab active" data-mode="login">Entrar</button><button class="tab" data-mode="signup">Criar conta</button></div><div id="auth-body">${authForm("login")}</div><small style="display:block;color:#617f9e;margin-top:14px">Modo demonstração: a conta local fica apenas neste navegador. No deploy, use o Worker + D1.</small></div></div>`;$("#mclose").onclick=closeModal;$$("[data-mode]").forEach(b=>b.onclick=()=>{state.authMode=b.dataset.mode;$("#auth-body").innerHTML=authForm(b.dataset.mode);authBind()});authBind()}
function authForm(mode){return `<div class="form-grid"><div class="field full"><label>Nome de usuário</label><input id="auth-name" placeholder="Seu nome"></div><div class="field full"><label>E-mail</label><input id="auth-email" type="email" placeholder="voce@email.com"></div><div class="field full"><label>Senha</label><input id="auth-pass" type="password" placeholder="••••••••"></div><div class="full"><button class="primary" id="auth-submit" style="width:100%">${mode==="login"?"Entrar":"Criar conta"}</button></div></div>`}
function authBind(){const b=$("#auth-submit");if(!b)return;b.onclick=async()=>{const name=$("#auth-name").value.trim()||"Kwai Game";const email=$("#auth-email").value.trim()||"demo@animedragon.local";const pass=$("#auth-pass").value;if(pass.length<4)return toast("Use uma senha com pelo menos 4 caracteres","err");const hp=await hashPass(pass);state.user={name,email,bio:"",passwordProof:hp,customAvatars:[]};store.set("ad_user",state.user);store.set("ad_avatar",state.avatar);closeModal();toast("Conta criada e sessão iniciada");render()}}
render();