const COOKIE='ad_session';
const SESSION_DAYS=30;
// Cloudflare Workers Free has a 10 ms CPU limit. Keep password KDF cost bounded for the free deployment.
const PBKDF2_ITERATIONS=12000;
const ANILIST='https://graphql.anilist.co';
const days=['Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado','Domingo'];
const jsonHeaders={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin','x-frame-options':'SAMEORIGIN'};
const ok=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{...jsonHeaders,...extra}});
const fail=(m,s=400)=>ok({error:m},s);
const now=()=>new Date().toISOString();
const slugify=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,110);
const cleanUrl=v=>{const s=String(v||'').trim();if(!s)return '';try{const u=new URL(s);return ['http:','https:'].includes(u.protocol)?u.toString():''}catch{return ''}};
const escJson=v=>JSON.stringify(v??[]);
async function sha256(v){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v)))].map(x=>x.toString(16).padStart(2,'0')).join('')}
function b64(a){let s='';for(const x of new Uint8Array(a))s+=String.fromCharCode(x);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function ub64(s){const p=s.replace(/-/g,'+').replace(/_/g,'/');const bin=atob(p+'='.repeat((4-p.length%4)%4));return Uint8Array.from(bin,c=>c.charCodeAt(0))}
async function passwordHash(password){const salt=crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:PBKDF2_ITERATIONS,hash:'SHA-256'},key,256);return `pbkdf2$${PBKDF2_ITERATIONS}$${b64(salt)}$${b64(bits)}`}
async function verifyPassword(password,stored){try{const [,iter,salt64,key64]=String(stored).split('$');const salt=ub64(salt64);const expected=ub64(key64);const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:Number(iter),hash:'SHA-256'},key,256));return bits.length===expected.length&&bits.every((x,i)=>x===expected[i])}catch{return false}}
function cookie(v,maxAge){return `${COOKIE}=${encodeURIComponent(v)}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=${maxAge}`}
function readCookies(req){const out={};for(const p of (req.headers.get('cookie')||'').split(';')){const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())}return out}
async function parseBody(req){const text=await req.text();if(text.length>3_000_000)throw new Error('Payload muito grande');return text?JSON.parse(text):{}}
async function dbAll(db,sql,...args){return (await db.prepare(sql).bind(...args).all()).results||[]}
async function dbFirst(db,sql,...args){return await db.prepare(sql).bind(...args).first()}
async function settings(db){const r=await dbFirst(db,"SELECT value FROM settings WHERE key='site'");const base={siteName:'AnimeDragon',tagline:'Seu universo de animes.',accent:'#ef1523',secondary:'#ff3b30',heroAutoplay:true,announcement:'',autoDiscover:true,navigation:[{id:'home',label:'Início',href:'#/'},{id:'anime',label:'Animes',href:'#/explore'},{id:'movies',label:'Filmes',href:'#/explore?type=Movie'},{id:'calendar',label:'Lançamentos',href:'#/calendar'}]};try{return {...base,...JSON.parse(r?.value||'{}')}}catch{return base}}
function tags(row){try{return JSON.parse(row.tags_json||'[]')}catch{return []}}
function cats(row){try{return JSON.parse(row.categories_json||'[]')}catch{return []}}
async function enrich(db,row){if(!row)return null;const ids=cats(row);let categories=[];if(ids.length)categories=await dbAll(db,`SELECT id,name,slug,color FROM categories WHERE id IN (${ids.map(()=>'?').join(',')})`,...ids);const count=await dbFirst(db,'SELECT COUNT(*) n FROM episodes WHERE anime_id=?',row.id);return {...row,featured:!!row.featured,tags:tags(row),categories,episodeCount:Number(count?.n||0),anilistId:row.anilist_id,malId:row.mal_id}}
async function listAnime(db,p){let sql='SELECT * FROM anime WHERE 1=1',args=[];const q=String(p.get('q')||'').trim();if(q){sql+=' AND (lower(title) LIKE ? OR lower(synopsis) LIKE ? OR lower(tags_json) LIKE ?)';const x=`%${q.toLowerCase()}%`;args.push(x,x,x)}if(p.get('type')){sql+=' AND type=?';args.push(p.get('type'))}if(p.get('status')){sql+=' AND status=?';args.push(p.get('status'))}if(p.get('category')){sql+=' AND categories_json LIKE ?';args.push(`%${JSON.stringify(Number(p.get('category')))}%`)}const sort=p.get('sort')||'popular';sql+=sort==='newest'?' ORDER BY datetime(created_at) DESC':sort==='rating'?' ORDER BY score DESC':sort==='title'?' ORDER BY lower(title) ASC':' ORDER BY views DESC,score DESC';sql+=' LIMIT 300';return dbAll(db,sql,...args)}
async function currentUser(db,req){const tok=readCookies(req)[COOKIE];if(!tok)return null;const h=await sha256(tok);const r=await dbFirst(db,'SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>? LIMIT 1',h,now());if(!r||r.blocked)return null;return r}
function safeUser(u){return u?{id:u.id,email:u.email,displayName:u.display_name,avatar:u.avatar||'',role:u.role,blocked:!!u.blocked,createdAt:u.created_at,lastLogin:u.last_login}:null}
async function sessionResponse(db,u){
  if(!u?.id) throw new Error('Usuário criado, mas não foi possível recuperar a conta.');
  const token=b64(crypto.getRandomValues(new Uint8Array(32)));
  const tokenHash=await sha256(token);
  const expires=new Date(Date.now()+SESSION_DAYS*864e5).toISOString();
  await db.prepare('DELETE FROM sessions WHERE user_id=? OR expires_at<=?').bind(u.id,now()).run();
  await db.prepare('INSERT INTO sessions(token_hash,user_id,expires_at,created_at) VALUES(?,?,?,?)').bind(tokenHash,u.id,expires,now()).run();
  return {user:safeUser(u),headers:{'Set-Cookie':cookie(token,SESSION_DAYS*86400)}}
}
async function requireUser(db,req){const u=await currentUser(db,req);return u||null}
async function requireAdmin(db,req){const u=await currentUser(db,req);return u&&u.role==='admin'?u:null}
async function log(db,u,action,target,meta={}){await db.prepare('INSERT INTO logs(admin_id,action,target,meta_json,created_at) VALUES(?,?,?,?,?)').bind(u?.id||null,action,target,JSON.stringify(meta),now()).run()}
async function animeBySlug(db,slug){return dbFirst(db,'SELECT * FROM anime WHERE slug=?',slug)}
async function sectionItems(db,s,u){let rows=[];if(s.type==='continue'&&u){rows=await dbAll(db,'SELECT a.* FROM history h JOIN anime a ON a.id=h.anime_id WHERE h.user_id=? ORDER BY h.updated_at DESC LIMIT 12',u.id)}else if(s.type==='trending'){rows=await dbAll(db,'SELECT * FROM anime ORDER BY views DESC,score DESC LIMIT 12')}else if(s.type==='featured'){rows=await dbAll(db,'SELECT * FROM anime WHERE featured=1 ORDER BY score DESC LIMIT 12')}else if(s.type==='latestEpisodes'){rows=await dbAll(db,'SELECT a.* FROM episodes e JOIN anime a ON a.id=e.anime_id GROUP BY a.id ORDER BY MAX(e.created_at) DESC LIMIT 12')}else if(s.type==='category'){rows=await dbAll(db,'SELECT * FROM anime WHERE categories_json LIKE ? ORDER BY views DESC LIMIT 12',`%${JSON.stringify(Number(s.category_id))}%`)}else{let ids=[];try{ids=JSON.parse(s.anime_ids_json||'[]')}catch{}if(ids.length)rows=await dbAll(db,`SELECT * FROM anime WHERE id IN (${ids.map(()=>'?').join(',')})`,...ids)}const out=[];for(const r of rows){const e=await enrich(db,r);if(e)out.push(e)}return out}
const AUTO_DEFAULT={enabled:true,intervalHours:6,yearMode:'current',maxPages:4,perPage:50,updated:0,discovered:0,lastRun:null,lastStatus:'never',lastError:'',lastDurationMs:0};
async function getAutomation(db){const r=await dbFirst(db,"SELECT value FROM settings WHERE key='automation'");try{return {...AUTO_DEFAULT,...JSON.parse(r?.value||'{}')}}catch{return {...AUTO_DEFAULT}}}
async function saveAutomation(db,patch){const next={...(await getAutomation(db)),...patch};await db.prepare("INSERT INTO settings(key,value) VALUES('automation',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(JSON.stringify(next)).run();return next}
const GENRE_MAP={Action:{name:'Ação',color:'#ef1523'},Adventure:{name:'Aventura',color:'#22c55e'},Comedy:{name:'Comédia',color:'#eab308'},Fantasy:{name:'Fantasia',color:'#8b5cf6'},Romance:{name:'Romance',color:'#ec4899'},Mystery:{name:'Mistério',color:'#64748b'},Thriller:{name:'Thriller',color:'#ef4444'},Horror:{name:'Terror',color:'#7c3aed'},Drama:{name:'Drama',color:'#f97316'},Sports:{name:'Esportes',color:'#06b6d4'},Music:{name:'Música',color:'#a855f7'},'Sci-Fi':{name:'Ficção científica',color:'#0ea5e9'},'Slice of Life':{name:'Slice of Life',color:'#84cc16'},Historical:{name:'Histórico',color:'#a16207'},Supernatural:{name:'Sobrenatural',color:'#6366f1'},Psychological:{name:'Psicológico',color:'#dc2626'},Ecchi:{name:'Ecchi',color:'#db2777'},Shounen:{name:'Shounen',color:'#3b82f6'},Isekai:{name:'Isekai',color:'#14b8a6'}};
async function ensureCategory(db,name){const slug=slugify(name);let row=await dbFirst(db,'SELECT * FROM categories WHERE slug=?',slug);if(row)return row;const meta=GENRE_MAP[name]||{name,color:'#64748b'};const r=await db.prepare('INSERT INTO categories(name,slug,color) VALUES(?,?,?)').bind(meta.name,slug,meta.color).run();return await dbFirst(db,'SELECT * FROM categories WHERE id=?',r.meta.last_row_id)}
async function ensureBaseSections(db){const n=Number((await dbFirst(db,'SELECT COUNT(*) n FROM sections'))?.n||0);if(n>0)return;const rows=[[1,'Continuando a jornada','Retome de onde parou','continue',null,'[]',1,1],[2,'Em alta agora','Os mais vistos pela comunidade','trending',null,'[]',1,2],[3,'Novos episódios','Direto do catálogo','latestEpisodes',null,'[]',1,3],[4,'Descobertas de 2026','Novos títulos do ano','featured',null,'[]',1,4]];for(const r of rows)await db.prepare('INSERT OR IGNORE INTO sections(id,title,subtitle,type,category_id,anime_ids_json,enabled,position) VALUES(?,?,?,?,?,?,?,?)').bind(...r).run()}
async function syncAniList(env){const db=env.DB;const started=Date.now();await ensureBaseSections(db);const cfg={...(await settings(db)),automation:await getAutomation(db)};const year=new Date().getUTCFullYear();let updated=0,discovered=0,categorized=0,pages=0;try{
 const q=`query($page:Int!,$perPage:Int!,$year:Int!){Page(page:$page,perPage:$perPage){pageInfo{hasNextPage,currentPage,lastPage}media(type:ANIME,isAdult:false,seasonYear:$year,sort:[UPDATED_AT_DESC,POPULARITY_DESC]){id,title{romaji english native},description,coverImage{extraLarge large},bannerImage,year,status,averageScore,episodes,format,genres,tags{name}}}}`;
 const maxPages=Math.max(1,Math.min(6,Number(cfg.automation?.maxPages||4))),perPage=Math.max(20,Math.min(50,Number(cfg.automation?.perPage||50)));
 for(let page=1;page<=maxPages;page++){
   const response=await fetch(ANILIST,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query:q,variables:{page,perPage,year}})});
   if(!response.ok) throw new Error(`AniList HTTP ${response.status}`);
   const j=await response.json(); if(j.errors?.length) throw new Error(j.errors.map(e=>e.message).join('; '));
   const media=j?.data?.Page?.media||[];pages=page;
   for(const m of media){
     const title=m.title?.english||m.title?.romaji||m.title?.native; if(!title)continue; const slug=slugify(title);
     let a=await dbFirst(db,'SELECT * FROM anime WHERE anilist_id=? OR slug=? LIMIT 1',m.id,slug);
     const genreNames=Array.isArray(m.genres)?m.genres.filter(Boolean):[]; let catIds=[];
     for(const g of genreNames){const c=await ensureCategory(db,g);if(c){catIds.push(c.id);categorized++}}
     for(const t of (m.tags||[]).slice(0,12)){if(t?.name&&!genreNames.includes(t.name))genreNames.push(t.name)}
     const special=genreNames.map(x=>String(x).toLowerCase()); if(special.includes('shounen') && !genreNames.includes('Shounen'))genreNames.push('Shounen'); if(special.includes('isekai') && !genreNames.includes('Isekai'))genreNames.push('Isekai');
     catIds=[]; for(const g of genreNames.filter(g=>GENRE_MAP[g])){const c=await ensureCategory(db,g);if(c)catIds.push(c.id)}
     catIds=[...new Set(catIds)];
     const score=Math.max(0,Math.min(10,Number(m.averageScore||0)/10));
     const featured=score>=8.5?1:0;
     const type=m.format==='MOVIE'?'Movie':(m.format||'TV').replace(/^SPECIAL$/,'OVA');
     if(a){
       await db.prepare('UPDATE anime SET title=?,slug=?,synopsis=?,cover=COALESCE(NULLIF(?,\'\'),cover),banner=COALESCE(NULLIF(?,\'\'),banner),year=?,status=?,score=?,type=?,episodes=?,featured=?,tags_json=?,categories_json=?,anilist_id=?,updated_at=? WHERE id=?')
         .bind(title,slug,String(m.description||'').replace(/<[^>]+>/g,'').slice(0,3000),cleanUrl(m.coverImage?.extraLarge||m.coverImage?.large),cleanUrl(m.bannerImage),m.year||year,m.status||a.status,score,type,Number(m.episodes||a.episodes||0),featured,JSON.stringify([...new Set(genreNames)].slice(0,20)),JSON.stringify([...new Set(catIds)]),m.id,now(),a.id).run();updated++;
     } else {
       const exists=await dbFirst(db,'SELECT id FROM anime WHERE slug=? OR anilist_id=? LIMIT 1',slug,m.id); if(exists)continue;
       await db.prepare('INSERT INTO anime(title,slug,synopsis,cover,banner,year,status,score,type,episodes,featured,views,tags_json,categories_json,anilist_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')
         .bind(title,slug,String(m.description||'').replace(/<[^>]+>/g,'').slice(0,3000),cleanUrl(m.coverImage?.extraLarge||m.coverImage?.large),cleanUrl(m.bannerImage),m.year||year,m.status||'NOT_YET_RELEASED',score,type,Number(m.episodes||0),featured,0,JSON.stringify([...new Set(genreNames)].slice(0,20)),JSON.stringify([...new Set(catIds)]),m.id,now(),now()).run();discovered++;
     }
   }
   if(!j?.data?.Page?.pageInfo?.hasNextPage)break;
 }
 await saveAutomation(db,{enabled:true,updated,discovered,lastRun:now(),lastStatus:'success',lastError:'',lastDurationMs:Date.now()-started});
 return {updated,discovered,categorized,pages,year,at:now(),durationMs:Date.now()-started};
 }catch(e){await saveAutomation(db,{lastRun:now(),lastStatus:'error',lastError:String(e?.message||e),lastDurationMs:Date.now()-started});throw e}}
async function ensureAdmin(env){const email=String(env.ADMIN_EMAIL||'').trim().toLowerCase();if(!email||!/^\S+@\S+\.\S+$/.test(email))return null;let u=await dbFirst(env.DB,'SELECT * FROM users WHERE email=? LIMIT 1',email);if(u){if(u.role!=='admin'){await env.DB.prepare("UPDATE users SET role='admin' WHERE id=?").bind(u.id).run();u=await dbFirst(env.DB,'SELECT * FROM users WHERE id=?',u.id)}return u}const ph=await passwordHash(String(env.ADMIN_PASSWORD||''));if(!env.ADMIN_PASSWORD)return null;try{await env.DB.prepare('INSERT INTO users(email,password_hash,display_name,role,created_at) VALUES(?,?,?,?,?)').bind(email,ph,'Administrador','admin',now()).run();return await dbFirst(env.DB,'SELECT * FROM users WHERE email=? LIMIT 1',email)}catch(e){console.error('ensureAdmin',e);return await dbFirst(env.DB,'SELECT * FROM users WHERE email=? LIMIT 1',email)}}
async function api(env,req){const db=env.DB;const url=new URL(req.url),p=url.pathname,m=req.method;
if(p==='/api/config'&&m==='GET'){try{const cats=await dbAll(db,'SELECT id,name,slug,color FROM categories ORDER BY name');let site=await settings(db);try{await db.prepare("INSERT OR IGNORE INTO settings(key,value) VALUES('site',?)").bind(JSON.stringify(site)).run()}catch{}return ok({settings:site,categories:cats})}catch(e){console.error('config',e);return ok({settings:{siteName:'AnimeDragon',tagline:'Seu universo de animes.',accent:'#ef1523',secondary:'#ff3b30',heroAutoplay:true,announcement:'',autoDiscover:true,navigation:[{id:'home',label:'Início',href:'#/'},{id:'anime',label:'Animes',href:'#/explore'},{id:'calendar',label:'Lançamentos',href:'#/calendar'}]},categories:[]})}}
if(p==='/api/home'&&m==='GET'){try{const u=await currentUser(db,req);const secs=await dbAll(db,'SELECT * FROM sections WHERE enabled=1 ORDER BY position');const sections=[];for(const s of secs){try{sections.push({...s,enabled:!!s.enabled,items:await sectionItems(db,s,u)})}catch(e){console.error('section error',s.id,e);sections.push({...s,enabled:!!s.enabled,items:[]})}}const heroRows=await dbAll(db,'SELECT * FROM anime WHERE featured=1 ORDER BY score DESC LIMIT 6');const hero=[];for(const a of heroRows){try{hero.push(await enrich(db,a))}catch(e){console.error('hero error',a.id,e)}}return ok({settings:await settings(db),hero,sections,user:safeUser(u)})}catch(e){console.error('home error',e);return ok({settings:await settings(db),hero:[],sections:[],user:null})}}
if(p==='/api/anime'&&m==='GET'){const rows=await listAnime(db,url.searchParams),items=[];for(const a of rows)items.push(await enrich(db,a));return ok({items,total:items.length,categories:await dbAll(db,'SELECT id,name,slug,color FROM categories ORDER BY name')})}
const ma=p.match(/^\/api\/anime\/([^/]+)$/);if(ma&&m==='GET'){const a=await animeBySlug(db,decodeURIComponent(ma[1]));if(!a)return fail('Anime não encontrado',404);const episodes=await dbAll(db,'SELECT * FROM episodes WHERE anime_id=? ORDER BY season,episode',a.id);const rel=await dbAll(db,'SELECT * FROM anime WHERE id<>? ORDER BY score DESC LIMIT 40',a.id);const related=[];for(const r of rel){if(cats(r).some(x=>cats(a).includes(x))&&related.length<8)related.push(await enrich(db,r))}await db.prepare('UPDATE anime SET views=views+1 WHERE id=?').bind(a.id).run();return ok({anime:await enrich(db,a),episodes,related})}
const mc=p.match(/^\/api\/anime\/([^/]+)\/comments$/);if(mc&&m==='GET'){const a=await animeBySlug(db,decodeURIComponent(mc[1]));if(!a)return fail('Anime não encontrado',404);const rows=await dbAll(db,'SELECT c.*,u.display_name FROM comments c JOIN users u ON u.id=c.user_id WHERE c.anime_id=? AND c.hidden=0 ORDER BY c.created_at DESC LIMIT 100',a.id);return ok({items:rows.map(x=>({...x,user:{id:x.user_id,displayName:x.display_name}}))})}
if(p==='/api/auth/register'&&m==='POST'){
  try{
    const b=await parseBody(req);
    const email=String(b.email||'').trim().toLowerCase();
    const pw=String(b.password||'');
    const dn=String(b.displayName||email.split('@')[0]||'Usuário').trim().slice(0,40) || 'Usuário';
    if(!/^\S+@\S+\.\S+$/.test(email)) return fail('Digite um e-mail válido.');
    if(pw.length<8) return fail('A senha precisa ter pelo menos 8 caracteres.');
    if(dn.length<2) return fail('Escolha um nome de exibição válido.');

    // Recheck first so duplicate registration is a friendly 409 rather than a generic 500.
    const existing=await dbFirst(db,'SELECT id FROM users WHERE email=? LIMIT 1',email);
    if(existing) return fail('E-mail já cadastrado. Entre na sua conta.',409);

    const ph=await passwordHash(pw);
    const createdAt=now();
    // OR IGNORE protects against two rapid registration requests racing each other.
    const result=await db.prepare('INSERT OR IGNORE INTO users(email,password_hash,display_name,avatar,role,created_at,last_login) VALUES(?,?,?,?,?,?,?)').bind(email,ph,dn,'','user',createdAt,createdAt).run();
    const u=await dbFirst(db,'SELECT * FROM users WHERE email=? LIMIT 1',email);
    if(!u) throw new Error('Cadastro não foi persistido no banco.');

    // Registration itself never has to depend on session creation.
    // The user is sent to login, where a fresh session is created normally.
    return ok({created:true,user:safeUser(u)},201);
  }catch(e){
    console.error('register error',e);
    const msg=String(e?.message||e||'');
    if(/UNIQUE constraint failed: users.email/i.test(msg)) return fail('E-mail já cadastrado. Entre na sua conta.',409);
    return fail('Não foi possível criar sua conta agora. Tente novamente.',500);
  }
}
if(p==='/api/auth/login'&&m==='POST'){
  try{
    await ensureAdmin(env);
    const b=await parseBody(req),email=String(b.email||'').trim().toLowerCase();
    let u=await dbFirst(db,'SELECT * FROM users WHERE email=? LIMIT 1',email);
    if(!u){
      const adminCfg=await ensureAdmin(env);
      if(adminCfg && adminCfg.email===email) u=adminCfg;
    }
    if(!u) return fail('E-mail ou senha inválidos.',401);
    if(u.blocked) return fail('Esta conta está bloqueada.',403);
    if(!(await verifyPassword(String(b.password||''),u.password_hash))) return fail('E-mail ou senha inválidos.',401);
    await db.prepare('UPDATE users SET last_login=? WHERE id=?').bind(now(),u.id).run();
    await db.prepare('DELETE FROM sessions WHERE user_id=?').bind(u.id).run();
    const fresh=await dbFirst(db,'SELECT * FROM users WHERE id=?',u.id);
    const sess=await sessionResponse(db,fresh);
    return ok({user:sess.user},200,sess.headers);
  }catch(e){console.error('login error',e);return fail('Não foi possível entrar agora. Tente novamente.',500)}
}
if(p==='/api/auth/logout'&&m==='POST'){const tok=readCookies(req)[COOKIE];if(tok)await db.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha256(tok)).run();return ok({ok:true},200,{'set-cookie':cookie('',0)})}
if(p==='/api/auth/me'&&m==='GET'){const u=await currentUser(db,req);if(!u)return fail('Não autenticado',401);return ok({user:safeUser(u)})}
if(p==='/api/me/profile'&&(m==='GET'||m==='PUT')){const u=await requireUser(db,req);if(!u)return fail('Não autenticado',401);if(m==='PUT'){const b=await parseBody(req);await db.prepare('UPDATE users SET display_name=?,avatar=? WHERE id=?').bind(String(b.displayName??u.display_name).trim().slice(0,40)||u.display_name,cleanUrl(b.avatar),u.id).run()}return ok({user:safeUser(await dbFirst(db,'SELECT * FROM users WHERE id=?',u.id))})}
if(p==='/api/me/library'&&m==='GET'){const u=await requireUser(db,req);if(!u)return fail('Não autenticado',401);const f=await dbAll(db,'SELECT a.* FROM favorites f JOIN anime a ON a.id=f.anime_id WHERE f.user_id=? ORDER BY f.created_at DESC',u.id),h=await dbAll(db,'SELECT a.*,h.episode_id,h.progress,h.updated_at history_updated FROM history h JOIN anime a ON a.id=h.anime_id WHERE h.user_id=? ORDER BY h.updated_at DESC',u.id);const fav=[];for(const a of f)fav.push(await enrich(db,a));const hist=[];for(const a of h)hist.push({anime:await enrich(db,a),animeId:a.id,episodeId:a.episode_id,progress:a.progress,updatedAt:a.history_updated});return ok({user:safeUser(u),favorites:fav,history:hist})}
const ml=p.match(/^\/api\/me\/(favorite|history)$/);if(ml&&(m==='POST'||m==='DELETE')){const u=await requireUser(db,req);if(!u)return fail('Não autenticado',401);const b=await parseBody(req),aid=Number(b.animeId);if(ml[1]==='favorite'){if(m==='POST')await db.prepare('INSERT OR IGNORE INTO favorites(user_id,anime_id,created_at) VALUES(?,?,?)').bind(u.id,aid,now()).run();else await db.prepare('DELETE FROM favorites WHERE user_id=? AND anime_id=?').bind(u.id,aid).run()}else{if(m==='POST')await db.prepare('INSERT INTO history(user_id,anime_id,episode_id,progress,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(user_id,anime_id) DO UPDATE SET episode_id=excluded.episode_id,progress=excluded.progress,updated_at=excluded.updated_at').bind(u.id,aid,Number(b.episodeId)||null,Math.max(0,Math.min(1,Number(b.progress)||0)),now()).run();else await db.prepare('DELETE FROM history WHERE user_id=? AND anime_id=?').bind(u.id,aid).run()}return ok({user:safeUser(await dbFirst(db,'SELECT * FROM users WHERE id=?',u.id))})}
if(p==='/api/comments'&&m==='POST'){const u=await requireUser(db,req);if(!u)return fail('Faça login para comentar.',401);const b=await parseBody(req),body=String(b.body||'').trim().slice(0,1200),aid=Number(b.animeId);if(!body)return fail('Comentário vazio.');if(!await dbFirst(db,'SELECT id FROM anime WHERE id=?',aid))return fail('Anime não encontrado',404);const r=await db.prepare('INSERT INTO comments(user_id,anime_id,body,created_at,updated_at) VALUES(?,?,?,?,?)').bind(u.id,aid,body,now(),now()).run();const c=await dbFirst(db,'SELECT c.*,u.display_name FROM comments c JOIN users u ON u.id=c.user_id WHERE c.id=?',r.meta.last_row_id);return ok({comment:{...c,user:{id:c.user_id,displayName:c.display_name}}})}
const cd=p.match(/^\/api\/comments\/(\d+)$/);if(cd&&m==='DELETE'){const u=await requireUser(db,req);if(!u)return fail('Não autenticado',401);const c=await dbFirst(db,'SELECT * FROM comments WHERE id=?',Number(cd[1]));if(!c)return fail('Comentário não encontrado',404);if(c.user_id!==u.id&&u.role!=='admin')return fail('Sem permissão',403);await db.prepare('UPDATE comments SET hidden=1,updated_at=? WHERE id=?').bind(now(),c.id).run();return ok({ok:true})}
const adminUser=await requireAdmin(db,req);if(!adminUser)return fail('Acesso administrativo necessário.',403);const admin=adminUser;
if(p==='/api/admin/stats'&&m==='GET'){const q=async t=>Number((await dbFirst(db,`SELECT COUNT(*) n FROM ${t}`))?.n||0);const sums=Number((await dbFirst(db,'SELECT COALESCE(SUM(views),0) n FROM anime'))?.n||0);return ok({users:await q('users'),admins:Number((await dbFirst(db,"SELECT COUNT(*) n FROM users WHERE role='admin'"))?.n||0),blocked:Number((await dbFirst(db,'SELECT COUNT(*) n FROM users WHERE blocked=1'))?.n||0),anime:await q('anime'),categories:await q('categories'),episodes:await q('episodes'),sections:await q('sections'),views:sums,lastLogs:await dbAll(db,'SELECT * FROM logs ORDER BY id DESC LIMIT 8')})}
if(p==='/api/admin/settings'&&m==='PUT'){const b=await parseBody(req),s={...await settings(db),...b};await db.prepare("INSERT INTO settings(key,value) VALUES('site',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(JSON.stringify(s)).run();await log(db,admin,'UPDATE_SETTINGS','site');return ok({settings:s})}
if(p==='/api/admin/users'&&m==='GET'){const rows=await dbAll(db,'SELECT * FROM users ORDER BY id DESC');return ok({items:rows.map(safeUser)})}
const ur=p.match(/^\/api\/admin\/users\/(\d+)\/(block|role)$/);if(ur&&m==='PATCH'){const id=Number(ur[1]);if(id===admin.id&&ur[2]==='role')return fail('Você não pode remover seu próprio admin.');const b=await parseBody(req);if(ur[2]==='block')await db.prepare('UPDATE users SET blocked=? WHERE id=?').bind(b.blocked?1:0,id).run();else if(['user','admin'].includes(b.role))await db.prepare('UPDATE users SET role=? WHERE id=?').bind(b.role,id).run();else return fail('Permissão inválida');await log(db,admin,ur[2]==='block'?(b.blocked?'BLOCK_USER':'UNBLOCK_USER'):'CHANGE_ROLE',String(id),b);return ok({user:safeUser(await dbFirst(db,'SELECT * FROM users WHERE id=?',id))})}
const ud=p.match(/^\/api\/admin\/users\/(\d+)$/);if(ud&&m==='DELETE'){const id=Number(ud[1]);if(id===admin.id)return fail('Você não pode remover sua própria conta.');await db.prepare('DELETE FROM users WHERE id=?').bind(id).run();await log(db,admin,'DELETE_USER',String(id));return ok({ok:true})}
if(p==='/api/admin/categories'&&m==='GET')return ok({items:await dbAll(db,'SELECT * FROM categories ORDER BY name')});
if(p==='/api/admin/categories'&&(m==='POST'||m==='PUT')){const b=await parseBody(req),name=String(b.name||'').trim().slice(0,80),slug=slugify(b.slug||name),color=/^#[0-9a-f]{6}$/i.test(String(b.color))?b.color:'#ef1523';if(!name)return fail('Nome obrigatório');if(m==='POST'){const r=await db.prepare('INSERT INTO categories(name,slug,color) VALUES(?,?,?)').bind(name,slug,color).run();await log(db,admin,'CREATE_CATEGORY',name);return ok({category:{id:r.meta.last_row_id,name,slug,color}})}await db.prepare('UPDATE categories SET name=?,slug=?,color=? WHERE id=?').bind(name,slug,color,Number(b.id)).run();await log(db,admin,'UPDATE_CATEGORY',String(b.id));return ok({category:{id:Number(b.id),name,slug,color}})}
const cdel=p.match(/^\/api\/admin\/categories\/(\d+)$/);if(cdel&&m==='DELETE'){await db.prepare('DELETE FROM categories WHERE id=?').bind(Number(cdel[1])).run();await log(db,admin,'DELETE_CATEGORY',cdel[1]);return ok({ok:true})}
if(p==='/api/admin/anime'&&m==='GET'){const rows=await dbAll(db,'SELECT * FROM anime ORDER BY created_at DESC');const items=[];for(const r of rows)items.push(await enrich(db,r));return ok({items,categories:await dbAll(db,'SELECT * FROM categories ORDER BY name')})}
if(p==='/api/admin/anime'&&(m==='POST'||m==='PUT')){const b=await parseBody(req),title=String(b.title||'').trim().slice(0,180),slug=slugify(b.slug||title),catsV=Array.isArray(b.categories)?b.categories.map(Number).filter(Number.isFinite):[];if(!title)return fail('Título obrigatório');const vals=[title,slug,String(b.synopsis||''),cleanUrl(b.cover),cleanUrl(b.banner),cleanUrl(b.logo),Number(b.year)||null,String(b.status||'Ongoing'),Math.max(0,Math.min(10,Number(b.score)||0)),String(b.type||'TV'),Number(b.episodes)||0,b.featured?1:0,Number(b.views)||0,String(b.releaseDay||''),String(b.releaseTime||''),JSON.stringify((b.tags||[]).map(String).slice(0,20)),JSON.stringify(catsV),Number(b.anilistId)||null,Number(b.malId)||null,now(),now()];if(m==='POST'){const r=await db.prepare('INSERT INTO anime(title,slug,synopsis,cover,banner,logo,year,status,score,type,episodes,featured,views,release_day,release_time,tags_json,categories_json,anilist_id,mal_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(...vals).run();await log(db,admin,'CREATE_ANIME',String(r.meta.last_row_id),{title});return ok({anime:await enrich(db,await dbFirst(db,'SELECT * FROM anime WHERE id=?',r.meta.last_row_id))})}await db.prepare('UPDATE anime SET title=?,slug=?,synopsis=?,cover=?,banner=?,logo=?,year=?,status=?,score=?,type=?,episodes=?,featured=?,views=?,release_day=?,release_time=?,tags_json=?,categories_json=?,anilist_id=?,mal_id=?,updated_at=? WHERE id=?').bind(...vals.slice(0,19),now(),Number(b.id)).run();await log(db,admin,'UPDATE_ANIME',String(b.id),{title});return ok({anime:await enrich(db,await dbFirst(db,'SELECT * FROM anime WHERE id=?',Number(b.id)))})}
const adel=p.match(/^\/api\/admin\/anime\/(\d+)$/);if(adel&&m==='DELETE'){await db.prepare('DELETE FROM anime WHERE id=?').bind(Number(adel[1])).run();await log(db,admin,'DELETE_ANIME',adel[1]);return ok({ok:true})}
if(p==='/api/admin/anime/bulk'&&m==='POST'){const b=await parseBody(req);let created=0;for(const raw of (b.items||[]).slice(0,500)){const title=String(raw.title||'').trim();if(!title)continue;const slug=slugify(raw.slug||title);if(await dbFirst(db,'SELECT id FROM anime WHERE slug=?',slug))continue;await db.prepare('INSERT INTO anime(title,slug,synopsis,cover,banner,year,status,score,type,episodes,featured,views,tags_json,categories_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(title,slug,String(raw.synopsis||''),cleanUrl(raw.cover),cleanUrl(raw.banner),Number(raw.year)||null,String(raw.status||'Ongoing'),Number(raw.score)||0,String(raw.type||'TV'),Number(raw.episodes)||0,raw.featured?1:0,0,JSON.stringify(raw.tags||[]),JSON.stringify(raw.categories||[]),now(),now()).run();created++}await log(db,admin,'BULK_CREATE_ANIME',String(created));return ok({created})}
if(p==='/api/admin/episodes'&&m==='GET'){const aid=Number(url.searchParams.get('animeId')||0);return ok({items:await dbAll(db,aid?'SELECT * FROM episodes WHERE anime_id=? ORDER BY anime_id,season,episode':'SELECT * FROM episodes ORDER BY anime_id,season,episode',...(aid?[aid]:[]))})}
if(p==='/api/admin/episodes/bulk'&&m==='POST'){const b=await parseBody(req),out=[];for(const raw of (b.items||[]).slice(0,1000)){const aid=Number(raw.animeId),ep=Number(raw.episode);if(!aid||!ep)continue;await db.prepare('INSERT INTO episodes(anime_id,season,episode,title,duration,language,stream_url,download_url,thumbnail,created_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(anime_id,season,episode) DO UPDATE SET title=excluded.title,duration=excluded.duration,language=excluded.language,stream_url=excluded.stream_url,download_url=excluded.download_url,thumbnail=excluded.thumbnail').bind(aid,Number(raw.season)||1,ep,String(raw.title||`Episódio ${ep}`),String(raw.duration||'24 min'),String(raw.language||'Legendado'),cleanUrl(raw.streamUrl),cleanUrl(raw.downloadUrl),cleanUrl(raw.thumbnail),now()).run();out.push(ep)}await log(db,admin,'BULK_UPSERT_EPISODES',String(out.length));return ok({created:out.length})}
const ed=p.match(/^\/api\/admin\/episodes\/(\d+)$/);if(ed&&m==='DELETE'){await db.prepare('DELETE FROM episodes WHERE id=?').bind(Number(ed[1])).run();await log(db,admin,'DELETE_EPISODE',ed[1]);return ok({ok:true})}
if(p==='/api/admin/sections'&&m==='GET')return ok({items:await dbAll(db,'SELECT * FROM sections ORDER BY position'),anime:await dbAll(db,'SELECT id,title FROM anime ORDER BY title')});
if(p==='/api/admin/sections'&&(m==='POST'||m==='PUT')){const b=await parseBody(req),title=String(b.title||'Nova seção').slice(0,100);const vals=[title,String(b.subtitle||''),String(b.type||'manual'),Number(b.categoryId)||null,JSON.stringify(Array.isArray(b.animeIds)?b.animeIds.map(Number).slice(0,100):[]),b.enabled===false?0:1,Number(b.position)||1];if(m==='POST'){const r=await db.prepare('INSERT INTO sections(title,subtitle,type,category_id,anime_ids_json,enabled,position) VALUES(?,?,?,?,?,?,?)').bind(...vals).run();await log(db,admin,'CREATE_SECTION',String(r.meta.last_row_id));return ok({section:{id:r.meta.last_row_id,title,subtitle:vals[1],type:vals[2],category_id:vals[3],anime_ids_json:vals[4],enabled:!!vals[5],position:vals[6]}})}await db.prepare('UPDATE sections SET title=?,subtitle=?,type=?,category_id=?,anime_ids_json=?,enabled=?,position=? WHERE id=?').bind(...vals,Number(b.id)).run();await log(db,admin,'UPDATE_SECTION',String(b.id));return ok({ok:true})}
const sd=p.match(/^\/api\/admin\/sections\/(\d+)$/);if(sd&&m==='DELETE'){await db.prepare('DELETE FROM sections WHERE id=?').bind(Number(sd[1])).run();await log(db,admin,'DELETE_SECTION',sd[1]);return ok({ok:true})}
if(p==='/api/admin/comments'&&m==='GET'){const rows=await dbAll(db,'SELECT c.*,u.display_name, a.title anime_title FROM comments c JOIN users u ON u.id=c.user_id JOIN anime a ON a.id=c.anime_id ORDER BY c.id DESC LIMIT 500');return ok({items:rows.map(c=>({...c,user:{id:c.user_id,displayName:c.display_name},animeTitle:c.anime_title}))})}
const ac=p.match(/^\/api\/admin\/comments\/(\d+)$/);if(ac&&m==='DELETE'){await db.prepare('UPDATE comments SET hidden=1,updated_at=? WHERE id=?').bind(now(),Number(ac[1])).run();await log(db,admin,'HIDE_COMMENT',ac[1]);return ok({ok:true})}
if(p==='/api/admin/automation'&&m==='GET'){return ok({automation:await getAutomation(db)})}
if(p==='/api/admin/automation'&&m==='PUT'){const b=await parseBody(req);const a=await saveAutomation(db,{enabled:b.enabled!==false,intervalHours:6,maxPages:Math.max(1,Math.min(6,Number(b.maxPages)||4)),perPage:Math.max(20,Math.min(50,Number(b.perPage)||50))});await log(db,admin,'UPDATE_AUTOMATION','anilist',a);return ok({automation:a})}
if(p==='/api/admin/anilist/discover'&&m==='POST'){const r=await syncAniList(env);await log(db,admin,'DISCOVER_ANIME',String(r.discovered),r);return ok(r)}
if(p==='/api/admin/anilist/sync'&&m==='POST'){const r=await syncAniList(env);await log(db,admin,'SYNC_ANILIST',String(r.updated),r);return ok(r)}
if(p==='/api/admin/export'&&m==='GET'){const tables=['settings','users','categories','anime','episodes','favorites','history','comments','sections','logs'];const data={};for(const t of tables)data[t]=await dbAll(db,`SELECT * FROM ${t}`);return ok(data,200,{'content-disposition':'attachment; filename="animedragon-backup.json"'})}
if(p==='/api/admin/import'&&m==='POST'){const b=await parseBody(req);for(const t of ['categories','anime','episodes','favorites','history','comments','sections','settings'])if(Array.isArray(b[t])){if(t==='settings')for(const r of b[t])await db.prepare('INSERT OR REPLACE INTO settings(key,value) VALUES(?,?)').bind(r.key,r.value).run();}await log(db,admin,'IMPORT_DATA','database');return ok({ok:true})}
if(p==='/api/admin/logs'&&m==='GET'){return ok({items:await dbAll(db,'SELECT * FROM logs ORDER BY id DESC LIMIT 500')})}
return fail('Endpoint não encontrado',404)}

export default {async fetch(req,env){try{const url=new URL(req.url);if(url.pathname.startsWith('/api/'))return await api(env,req);const res=await env.ASSETS.fetch(req);return res}catch(e){console.error('request error',e);return fail('Erro interno',500)}},async scheduled(_event,env){try{await ensureAdmin(env);const a=await getAutomation(env.DB);if(a.enabled!==false)await syncAniList(env)}catch(e){console.error('cron sync',e)}}};
